services:                                                                                                                                       
  postgres:                                                                                                                                     
    image: postgres:13                                                                                                                         
    environment:                                                                                                                                
      POSTGRES_USER: airflow                                                                                                                    
      POSTGRES_PASSWORD: airflow                                                                                                                
      POSTGRES_DB: airflow                                                                                                                      
    volumes:                                                                                                                                    
      - postgres_data:/var/lib/postgresql/data                                                                                                  
                                                                                                                                                
  redis:                                                                                                                                        
    image: redis:latest                                                                                                                         
                                                                                                                                                
  webserver:                                                                                                                                    
    image: apache/airflow:2.6.3                                                                                                                 
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor                                                                                                   
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow                                                   
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow                                                         
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0                                                                                         
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='                                                                                              
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'                                                                                                      
    volumes:                                                                                                                                    
      - ./dags:/opt/airflow/dags                                                                                                                
    ports:
      - "8080:8080"
    depends_on:
      - init
    command: webserver                                                                                                                          
                                                                                                                                                
  scheduler:                                                                                                                                    
    image: apache/airflow:2.6.3                                                                                                                 
    environment:                                                                                                                                
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor                                                                                                   
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow                                                   
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow                                                         
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0                                                                                         
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='                                                                                              
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'                                                                                                      
    volumes:                                                                                                                                    
      - ./dags:/opt/airflow/dags                                                                                                                
    depends_on:                                                                                                                                 
      - init
    command: scheduler                                                                                                                          
                                                                                                                                                
  init:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: 'WEnN4kNtuSmRwJC6RZenXg=='
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'WEnN4kNtuSmRwJC6RZenXg=='
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'WEnN4kNtuSmRwJC6RZenXg=='
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__WEBSERVER__SECRET_KEY: 'WEnN4kNtuSmRwJC6RZenXg=='
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'WEnN4kNtuSmRwJC6RZenXg=='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'WEnN4kNtuSmRwJC6RZenXg=='
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
      - redis
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: on-failure

  worker:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - init
    command: celery worker

volumes:
  postgres_data:
