version: '2.4'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"  # Web UI NameNode
      - "9000:9000"  # HDFS
    environment:
      - CLUSTER_NAME=ibra-hadoop-cluster
    volumes:
      - namenode:/hadoop/dfs/name
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      namenode:
        condition: service_healthy

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    ports:
      - "8088:8088"  # Web UI ResourceManager
    depends_on:
      namenode:
        condition: service_healthy

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    depends_on:
      resourcemanager:
        condition: service_started

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "19888:19888"  # Web UI History Server
    depends_on:
      namenode:
        condition: service_healthy
      resourcemanager:
        condition: service_started

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    restart: always
    environment:
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master порт
    depends_on:
      namenode:
        condition: service_healthy
      resourcemanager:
        condition: service_started

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    restart: always
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      spark-master:
        condition: service_started

volumes:
  namenode:
  datanode:
